apiVersion: apps/v1beta1
kind: StatefulSet

metadata:
  name: zookeeper1
  namespace: default
  annotations:
      contact: adaickalavan <adaickalavan@gmail.com> 

spec:
  replicas: 1

  selector:
    matchLabels:
      app: zookeeper1

  serviceName: zk1-service

  template:
    metadata:
      name: zookeeper1
      labels:
        app: zookeeper1
    spec:
      containers:
        - name: zookeeper1
          image: confluentinc/cp-zookeeper
          imagePullPolicy: IfNotPresent
          ports:    
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          env:
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"   
          resources:

---
kind: Service
apiVersion: v1
metadata:
  name: zk1-service
  namespace: default

spec:
  type: NodePort

  selector:
    app: zookeeper1

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port     - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - name: zk1-2181
      port: 2181

---
apiVersion: apps/v1beta1
kind: StatefulSet

metadata:
  name: kafka1
  namespace: default
  annotations:
      contact: adaickalavan <adaickalavan@gmail.com> 

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kafka1

  serviceName: kf1-service

  template:
    metadata:
      name: kafka1
      labels:
        app: kafka1
    spec:
      containers:
        - name: kafka1
          image: confluentinc/cp-kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 19091
            - containerPort: 19092
            - containerPort: 19093
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zk1-service:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: BROK://:19091, PROD://:19092, CONS://:19093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: BROK:PLAINTEXT, PROD:PLAINTEXT, CONS:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: BROK

            - name: KAFKA_REPLICA_FETCH_MAX_BYTES
              value: "100000000" #100MB. (defaults to 1MB). message.max.bytes <= replica.fetch.max.bytes 
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "100000000" #100MB. (defaults to 1MB). message.max.bytes <= replica.fetch.max.bytes
            - name: KAFKA_LOG_CLEANUP_POLICY
              value: delete #Cleanup policy for segments beyond the retention window
            - name: KAFKA_LOG_RETENTION_MINUTES
              value: "1" #Number of minutes to keep a log file before deleting. Default 168 hours.
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          resource:

---
kind: Service
apiVersion: v1
metadata:
  name: kf1-service
  namespace: default

spec:
  type: NodePort

  selector:
    app: kafka1

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port     - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - name: kf1-brok-port
      port: 19091
    - name: kf1-prod-port
      port: 19092
    - name: kf1-cons-port
      port: 19093
