apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: goproducer-deployment
  labels:
    app: goproducer-deployment
    release: stable
    environment: dev
  annotations:
      contact: adaickalavan <adaickalavan@gmail.com> 

spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: goproducer
      release: stable
      environment: dev

  template:
    metadata:
      name: goproducer
      labels:
        app: goproducer
        release: stable
        environment: dev
    spec:
      containers:
        - name: goproducer
          image: goproducer
          imagePullPolicy: IfNotPresent
          env:
            - name: TOPICNAME
              value: video1
            - name: KAFKAPORT
              value: kafka1:9093
            - name: COMPRESSIONTYPE
              value: gzip   
          resources:
          securityContext:
              privileged: true  
