apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: goproducer-deployment

spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      release: stable

  template:
    metadata:
      name: goproducer
      labels:
        release: stable
        environment: dev
      annotations:
        contact: adaickalavan <adaickalavan@gmail.com> 
    spec:
      volumes:
        - name: display
          hostPath:
            path: /tmp/.X11-unix
        - name: camera
          hostPath: 
            path: /dev/video0     
      containers:
        - name: goproducer
          image: goproducer
          imagePullPolicy: IfNotPresent
          env:
            - name: TOPICNAME
              value: video1
            - name: KAFKAPORT
              value: kafka1:9093
            - name: COMPRESSIONTYPE
              value: gzip
            - name: VIDEODEVICE
              value: "0"
            - name: DISPLAY
              value: $DISPLAY      
          volumeMounts:
            - name: display 
              mountPath: /tmp/.X11-unix
          volumeDevices:
            - name: camera
              devicePath: /dev/video0          
          resources:

