apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: goconsumer
  annotations:
      contact: adaickalavan <adaickalavan@gmail.com> 

spec:
  replicas: 1
  
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1

  selector:
    matchLabels:
      app: goconsumer

  template:
    metadata:
      name: goconsumer
      labels:
        app: goconsumer
    spec:
      containers:
        - name: goconsumer
          image: goconsumer
          imagePullPolicy: IfNotPresent
          env:
            - name: TOPICNAME
              value: video1
            - name: KAFKAPORT
              value: kf1-service:19093
            - name: GROUPNAME
              value: goconsumer 
            - name: MLURL1
              value: tfserving:8501/v1/models/tfModel:predict
            - MLLABELS1=/data/labels/imagenetLabels.json  
          resources:
          volumeMounts:
      - MLLABELS1=/data/labels/imagenetLabels.json
      - /home/administrator/GoWorkspace/src/github.com/adaickalavan/Scalable-Deployment/tensorflowserving/resnet/1538687457/assets:/data/labels
    